from django.urls import path

from redactors_tracking.views import (index,
                                      TopicListView,
                                      TopicCreateView,
                                      TopicUpdateView,
                                      TopicDeleteView,
                                      NewspaperListView,
                                      NewspaperDetailView,
                                      NewspaperUpdateView,
                                      NewspaperCreateView,
                                      NewspaperDeleteView,
                                      RedactorListView,
                                      RedactorUpdateView,
                                      RedactorDetailView,
                                      RedactorCreateView,
                                      RedactorDeleteView,
                                      newspaper_add_redactor,
                                      newspaper_delete_redactor)

urlpatterns = [
    path("",
         index,
         name="index"),
    path("topics/",
         TopicListView.as_view(),
         name="topic-list"),
    path("topics/create/",
         TopicCreateView.as_view(),
         name="topic-create"),
    path("topics/<int:pk>/update/",
         TopicUpdateView.as_view(),
         name="topic-update"),
    path("topics/<int:pk>/delete/",
         TopicDeleteView.as_view(),
         name="topic-delete"),
    path("newspapers/",
         NewspaperListView.as_view(),
         name="newspaper-list"),
    path("newspapers/create/",
         NewspaperCreateView.as_view(),
         name="newspaper-create"),
    path("newspapers/<int:pk>/detail",
         NewspaperDetailView.as_view(),
         name="newspaper-detail"),
    path("newspapers/<int:pk>/update",
         NewspaperUpdateView.as_view(),
         name="newspaper-update"),
    path("newspapers/<int:pk>/delete",
         NewspaperDeleteView.as_view(),
         name="newspaper-delete"),
    path("redactors/",
         RedactorListView.as_view(),
         name="redactor-list"),
    path("redactors/<int:pk>/update/",
         RedactorUpdateView.as_view(),
         name="redactor-update"),
    path("redactors/<int:pk>/detail",
         RedactorDetailView.as_view(),
         name="redactor-detail"),
    path("redactors/create",
         RedactorCreateView.as_view(),
         name="redactor-create"),
    path("redactors/<int:pk>/delete",
         RedactorDeleteView.as_view(),
         name="redactor-delete"),
    path("newspapers/<int:pk>/add-redactor/",
         newspaper_add_redactor,
         name="redactor-add-newspaper"),
    path("newspapers/<int:pk>/delete-redactor/",
         newspaper_delete_redactor,
         name="redactor-delete-newspaper"),
]

app_name = "redactors_tracking"
