# Generated by Django 4.2.7 on 2023-12-03 12:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("redactors_tracking", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="redactor",
            old_name="redactor_id",
            new_name="license",
        ),
    ]
